title: ACX Reader
tagline: Because Substack is too damn slow
description: Because Substack is too damn slow
url: https://acxreader.github.io
# logo: /assets/img/echo1.png
# image: /assets/img/embed.png
# twitter:
#   card: summary_large_image
# google_site_verification:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

permalink: /p/:title

theme: minima
header_pages:
  - about.md
  - acx.md

# try to destroy feed
feed:
  posts_limit: 0
  path: /

# remove backlinks with U+200B
kramdown:
  footnote_backlink:

future: true
